controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_homepage:
    path: /
    controller: App\AppBundle\Controller\DefaultController::indexAction
    methods: GET

app_login:
    path: /login
    controller: App\AppBundle\Controller\SecurityController::loginAction
    methods: [GET, POST]

app_login_check:
    path: /login_check
    controller: App\AppBundle\Controller\SecurityController::loginCheck
    methods: [GET]

app_logout:
    path: /logout
    controller: App\AppBundle\Controller\SecurityController::logoutCheck
    methods: [GET]

app_user_create:
    path: /users/create
    controller: App\AppBundle\Controller\UserController::createAction
    methods: [GET, POST]
